version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/deployment"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      major:
        update-types:
          - "major"
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
