version: '3'
services:
    db:
        image: postgres:13.13
        restart: always
        environment:
            POSTGRES_PASSWORD: fake_db_password
            POSTGRES_USER: fake_db_user
            POSTGRES_DB: db
        volumes:
            - ./docker/postgres/scripts:/docker-entrypoint-initdb.d

    run_migrations:
        build: .
        command: ../scripts/run_migrations.sh
        env_file: .env
        depends_on:
            - db
        links:
            - db

    collect_static:
        build: .
        command: ../scripts/collect_static.sh
        env_file: .env

    lengcol:
        build: .
        restart: always
        env_file: .env
        depends_on:
            - db
        links:
            - db

    web:
        image: nginx:1.25.3
        restart: always
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 80:80
        depends_on:
            - lengcol
        links:
            - lengcol
            - grafana

    celery_worker:
        build: .
        command: celery -A lengcol.celery worker --loglevel=info --logfile=/var/log/celery/worker.log
        restart: always
        env_file: .env
        depends_on:
            - db
            - redis_broker
        links:
            - db
            - redis_broker

    redis_broker:
        image: redis:7.2.3
        restart: always
        sysctls:
            net.core.somaxconn: 511

    prometheus:
        image: prom/prometheus:v2.48.0
        volumes:
            - ./docker/prometheus/config/alerts_probes_rules.yml:/etc/prometheus/alerts_probes_rules.yml
        links:
            - blackbox_exporter

    alertmanager:
        image: prom/alertmanager:v0.26.0
        links:
            - prometheus
        depends_on:
            - prometheus

    blackbox_exporter:
        image: prom/blackbox-exporter:v0.24.0
        links:
          - lengcol

    grafana:
        image: grafana/grafana:10.2.2
        links:
            - prometheus
            - alertmanager
            - redis_broker
        depends_on:
            - prometheus

    loki:
        image: grafana/loki:2.9.2
        links:
            - lengcol
            - grafana
        depends_on:
            - lengcol

    promtail:
        image: grafana/promtail:2.9.2
        links:
            - loki
        depends_on:
            - loki
