version: '3'
services:
    db:
        image: postgres:12.3
        restart: always
        environment:
            POSTGRES_PASSWORD: fake_db_password
            POSTGRES_USER: fake_db_user
            POSTGRES_DB: db
        volumes:
            - ./docker/db/pg_data:/var/lib/postgresql/data

    run_migrations:
        build: .
        command: ../scripts/run_migrations.sh
        env_file: .env
        depends_on:
            - db
        links:
            - db

    collect_static:
        build: .
        command: ../scripts/collect_static.sh
        env_file: .env
        volumes:
            - ./docker/static:/opt/lengcol/lengcol/lengcol/static

    lengcol:
        build: .
        restart: always
        env_file: .env
        depends_on:
            - db
        links:
            - db
        volumes:
            - ./lengcol:/opt/lengcol/lengcol/

    web:
        image: nginx:1.19.2
        restart: always
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 80:80
        depends_on:
            - lengcol
        links:
            - lengcol
            - grafana

    celery_worker:
        build: .
        command: celery -A lengcol.celery worker --loglevel=info
        restart: always
        env_file: .env
        depends_on:
            - db
            - redis_broker
        links:
            - db
            - redis_broker

    redis_broker:
        image: redis:6.0.7
        restart: always
        sysctls:
            net.core.somaxconn: 511

    prometheus:
        image: prom/prometheus:v2.20.1
        links:
          - blackbox_exporter
        volumes:
            - ./docker/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml

    blackbox_exporter:
        image: prom/blackbox-exporter
        links:
          - lengcol

    grafana:
        image: grafana/grafana:7.1.5
        links:
            - prometheus
        depends_on:
            - prometheus
