version: '3'
services:
    db:
        volumes:
            - ./docker/db/pg_data:/var/lib/postgresql/data

    collect_static:
        volumes:
            - ./docker/static:/opt/lengcol/lengcol/lengcol/static

    lengcol:
        volumes:
            - ./lengcol:/opt/lengcol/lengcol/
            - ./docker/logs/gunicorn/:/var/log/gunicorn/

    celery_worker:
        volumes:
            - ./docker/logs/celery/:/var/log/celery/

    prometheus:
        ports:
            - 9090:9090
        volumes:
            - ./docker/prometheus/config/:/etc/prometheus/

    alertmanager:
        ports:
            - 9093:9093
    grafana:
        ports:
            - 3000:3000
