version: '3'
services:
    db:
        volumes:
            - ./docker/db/pg_data:/var/lib/postgresql/data

    lengcol:
        volumes:
            - ./lengcol:/opt/lengcol/lengcol/

    prometheus:
        ports:
            - 9090:9090

    alertmanager:
        ports:
            - 9093:9093
    grafana:
        ports:
            - 3000:3000
