version: '3'
services:
    db:
        volumes:
            - /data/db/pg_data:/var/lib/postgresql/data

    collect_static:
        volumes:
            - /data/static:/opt/lengcol/lengcol/lengcol/static

    lengcol:
        volumes:
            - /data/static:/opt/lengcol/lengcol/lengcol/static

    web:
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./docker/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
            - /data/certbot/conf:/etc/letsencrypt
            - /data/certbot/www:/var/www/certbot

    certbot:
        image: certbot/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        volumes:
            - /data/certbot/conf:/etc/letsencrypt
            - /data/certbot/www:/var/www/certbot
