version: '3'
services:
    db:
        volumes:
            - /data/db/pg_data:/var/lib/postgresql/data

    collect_static:
        volumes:
            - /data/static:/opt/lengcol/lengcol/lengcol/static

    lengcol:
        restart: always
        command: gunicorn "lengcol.wsgi:application" -c "../docker/gunicorn/settings/prod.py"
        volumes:
            - /data/static:/opt/lengcol/lengcol/lengcol/static
            - /data/logs/gunicorn/:/var/log/gunicorn/
    web:
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./docker/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
            - /data/logs/nginx/:/var/log/nginx/
            - /data/certbot/conf:/etc/letsencrypt
            - /data/certbot/www:/var/www/certbot

    certbot:
        image: certbot/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        volumes:
            - /data/certbot/conf:/etc/letsencrypt
            - /data/certbot/www:/var/www/certbot

    logrotate:
        build: ./docker/logrotate/
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do logrotate -v logrotate.conf; sleep 12h & wait $${!}; done;'"
        depends_on:
            - web
        volumes:
            - /data/logs/nginx/:/var/log/nginx/
            - /data/logs/gunicorn/:/var/log/gunicorn/
            - /var/run/docker.sock:/var/run/docker.sock
