- name: Install fail2ban
  become: true
  package:
    name: fail2ban
    state: present

- name: Upload local iptables multiport config
  become: true
  copy:
    src: files/fail2ban/action.d/iptables-multiport.local
    dest: /etc/fail2ban/action.d/iptables-multiport.local
    owner: root
    group: root
    mode: '644'

- name: Upload local jail config file
  become: true
  copy:
    src: files/fail2ban/jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '644'

- name: Upload nginx-444 jail
  become: true
  copy:
    src: files/fail2ban/filter.d/nginx-444.conf
    dest: /etc/fail2ban/filter.d/nginx-444.conf
    owner: root
    group: root
    mode: '644'

- name: Upload nginx-400 jail
  become: true
  copy:
    src: files/fail2ban/filter.d/nginx-400.conf
    dest: /etc/fail2ban/filter.d/nginx-400.conf
    owner: root
    group: root
    mode: '644'

- name: Upload dashboard-failed-logins
  become: true
  copy:
    src: files/fail2ban/filter.d/dashboard-failed-logins.conf
    dest: /etc/fail2ban/filter.d/dashboard-failed-logins.conf
    owner: root
    group: root
    mode: '644'

- name: Upload local paths-overrides config file
  become: true
  copy:
    src: files/fail2ban/paths-overrides.local
    dest: /etc/fail2ban/paths-overrides.local
    owner: root
    group: root
    mode: '644'

- name: Ensure fail2ban service is running
  become: true
  service:
    name: fail2ban
    state: restarted
