- name: Create project folder
  become: true
  file:
    path: /opt/apps
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '700'

- name: Get project
  git:
    repo: 'https://github.com/bartsanchez/lengcol.git'
    dest: /opt/apps/lengcol

- name: Upload env file
  copy:
    src: files/encrypted_env
    dest: /opt/apps/lengcol/.env
    decrypt: yes
    owner: ubuntu
    group: ubuntu
    mode: '400'
