# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='value',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
