# Generated by Django 2.2.2 on 2019-06-25 21:50

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("definitions", "0005_example"),
    ]

    operations = [
        migrations.AddField(
            model_name="definition",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
