# Generated by Django 2.2.2 on 2019-06-25 21:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0006_definition_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
