# Generated by Django 2.2.2 on 2019-08-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0008_definition_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='example',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='term',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
