# Generated by Django 3.1.5 on 2021-01-28 22:12

import tagging.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("definitions", "0009_add_active_fields_to_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="definition",
            name="tags",
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
