# Generated by Django 3.2 on 2021-05-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0011_update_site_domain_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='definition',
            options={'ordering': ['created']},
        ),
    ]
