# Generated by Django 3.2 on 2021-05-02 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("definitions", "0012_alter_definition_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="term",
            options={"ordering": ["created"]},
        ),
    ]
