# Generated by Django 3.2 on 2021-05-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("definitions", "0014_definition_definitions_created_0b5729_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="term",
            index=models.Index(
                fields=["created"], name="definitions_created_8d3d65_idx"
            ),
        ),
    ]
