# Generated by Django 4.2.8 on 2023-12-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("definitions", "0015_term_definitions_created_8d3d65_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="term",
            name="value",
            field=models.CharField(unique=True),
        ),
    ]
