server:
  disable: true

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          host: lengcol
          __path__: /var/log/nginx/{access,error}.log*
    pipeline_stages:
    - match:
        selector: '{job="nginx"}'
        stages:
        - regex:
            expression: '^(?P<remote_addr>[\w\.]+) - (?P<remote_user>[^ ]*) \[(?P<time_local>.*)\] "(?P<method>[^ ]*) (?P<request>[^ ]*) (?P<protocol>[^ ]*)" (?P<status>[\d]+) (?P<body_bytes_sent>[\d]+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)"?'
        - labels:
            remote_addr:
            #remote_user:
            #time_local:
            method:
            request:
            #protocol:
            status:
            #body_bytes_sent:
            http_referer:
            http_user_agent:
  - job_name: gunicorn
    static_configs:
      - targets:
          - localhost
        labels:
          job: gunicorn
          host: lengcol
          __path__: /var/log/gunicorn/{access,error,recaptcha}.log*
