---
- hosts: lengcolaws
  remote_user: ubuntu
  tasks:
    - import_tasks: tasks/pre_install.yml

    - import_tasks: tasks/setup_repo.yml

    - import_tasks: tasks/setup_alertmanager_config.yml

    - import_tasks: tasks/fail2ban.yml

    - name: Prune dangling images
      shell:
        chdir: /opt/apps/lengcol
        cmd: docker image prune -f

    - name: Prune volumes
      shell:
        chdir: /opt/apps/lengcol
        cmd: docker volume prune -f

    - name: Pull new images
      shell:
        chdir: /opt/apps/lengcol
        cmd: make pull ENV=prod

    - name: Build containers
      shell:
        chdir: /opt/apps/lengcol
        cmd: make build ENV=prod

    - name: Stop running containers
      shell:
        chdir: /opt/apps/lengcol
        cmd: make stop ENV=prod

    - name: Start containers
      shell:
        chdir: /opt/apps/lengcol
        cmd: make run ENV=prod

    - import_tasks: tasks/post_install.yml
