---
- hosts: lengcolaws
  remote_user: ubuntu
  tasks:
    - name: Create project folder
      become: true
      file:
        path: /opt/apps
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '700'

    - name: Get project
      git:
        repo: 'https://github.com/bartsanchez/lengcol.git'
        dest: /opt/apps/lengcol

    - name: Upload env file
      copy:
        src: files/encrypted_env
        dest: /opt/apps/lengcol/.env
        decrypt: yes
        owner: ubuntu
        group: ubuntu
        mode: '400'

    - name: Install fail2ban
      become: true
      package:
        name: fail2ban
        state: present

    - name: Build containers
      shell:
        chdir: /opt/apps/lengcol
        cmd: docker-compose -f docker-compose.yml -f docker-compose.prod.yml build

    - name: Stop running containers
      shell:
        chdir: /opt/apps/lengcol
        cmd: docker-compose -f docker-compose.yml -f docker-compose.prod.yml down

    - name: Start containers
      shell:
        chdir: /opt/apps/lengcol
        cmd: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
