---
- hosts: lengcolaws
  remote_user: ubuntu
  tasks:
    - name: Create project folder
      become: true
      file:
        path: /opt/apps
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '700'

    - name: Get project
      git:
        repo: 'https://github.com/bartsanchez/lengcol.git'
        dest: /opt/apps/lengcol

    - name: Create env file
      file:
        path: /opt/apps/lengcol/.env
        state: touch
        owner: ubuntu
        group: ubuntu
        mode: '400'

    - name: Build containers
      shell:
        chdir: /opt/apps/lengcol
        cmd: docker-compose build
