name: Deploy

on:
  push:
    branches: [master]

jobs:
  deployment:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r deployment/requirements.txt

      - name: Deploy
        run: make deploy
        env:
          AWS_KEY_PAIR_PEM_FILE: ${{ secrets.AWS_KEY_PAIR_PEM_FILE }}
          VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
          ANSIBLE_HOST_KEY_CHECKING: False
