name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Tox and any other packages
        run: pip install tox

      - name: Run unit tests
        # Run tox using the version of Python in `PATH`
        run: tox -e py

      - name: Run flake8
        run: tox -e flake8

      - name: Run isort-seed-config
        run: tox -e isort-seed-config

      - name: Run isort
        run: tox -e isort
